First = (input("first number\n"))
Second = (input("second number\n"))
results = int(First) + int(Second)
results1 = int(First) - int(Second)
results2 = int(First) * int(Second)
results3 = int(First) / int(Second)
print("Sum is " + str(results) + "\n") 
print("Subtraction  is " + str(results1) + "\n")
print("Multiplication  is " + str(results2) + "\n")
print("Division is " + str(results3) + "\n")
